import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import JuancaPic from "../public/juanca.png";
import Layout from "@/layout/Layout";
import { ReactElement } from "react";
import JavaScript from "@/public/svg/javascript.svg";
import TypeScript from "@/public/svg/typescript.svg";
import Reactjs from "@/public/svg/reactjs.svg";
import Nextjs from "@/public/svg/nextjs.svg";
import Git from "@/public/svg/git.svg";
import Nodejs from "@/public/svg/nodejs.svg";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const skills = [
    {
      name: "JavaScript",
      icon: "typescript",
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`flex mt-[10vh] max-h-[90vh] w-fit lg:px-20`}>
        <div className="pb-4 m-4 px-6 rounded-2xl  drop-shadow-xl bg-[#402166]/50 lg:bg-[#221A37]/0">
          <p className="text-[#5D3974] mt-4">Front End</p>
          <h2 className="font-PageTitle font-bold text-slate-50 text-4xl">
            Web Developer
          </h2>
          <p className=" mt-3 font-PageTitle text-slate-300">
            Juan Carlos Ortiz Drada
          </p>

          <p className="mt-5 font-PageTitle text-slate-200">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
            veritatis deserunt officia nesciunt distinctio at eos ipsam rem qui
            reiciendis id. Fuga doloribus voluptatem iste adipisci ut beatae
            veritatis pariatur! Lorem, ipsum dolor sit amet consectetur
            adipisicing elit. Aliquid doloribus temporibus aut odit dolorem
            veniam qui laudantium nisi accusantium quasi nam, veritatis
            molestiae debitis fuga nostrum facilis assumenda. Dicta, temporibus?
          </p>
          <p className="text-slate-300 mt-4">I usually work with:</p>
          <div className="mt-6 mb-5 gap-4 grid grid-cols-5 justify-tems-center sm:grid-cols-6 mt-4 drop-shadow h-fit pb-4">
            <div className="grid justify-items-center text-slate-300 text-sm">
              <Image
                className=""
                src={JavaScript}
                alt={"javascript icon"}
                height={"45"}
                width={"45"}
              />
              <p>JavaScript</p>
            </div>
            <div className="grid justify-items-center text-slate-300 text-sm">
              <Image
                className=""
                src={TypeScript}
                alt={"typescript icon"}
                height={"45"}
                width={"45"}
              />
              <p>TypeScript</p>
            </div>
            <div className="grid justify-items-center text-slate-300 text-sm">
              <Image
                className=""
                src={Reactjs}
                alt={"react.js icon"}
                height={"45"}
                width={"45"}
              />
              <p>React.js</p>
            </div>
            <div className="grid justify-items-center text-slate-300 text-sm">
              <Image
                className=""
                src={Nextjs}
                alt={"next.js icon"}
                height={"45"}
                width={"45"}
              />
              <p>Next.js</p>
            </div>
            <div className="grid justify-items-center text-slate-300 text-sm">
              <Image
                className=""
                src={Nodejs}
                alt={"node.js icon"}
                height={"45"}
                width={"45"}
              />
              <p>Node.js</p>
            </div>
            <div className="grid justify-items-center text-slate-300 text-sm">
              <Image
                className=""
                src={Git}
                alt={"git icon"}
                height={"45"}
                width={"45"}
              />
              <p>Git</p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
