import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import JuancaPic from "../public/juanca.png";
import Layout from "@/layout/Layout";
import { ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });
const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`flex w-fit justify-center`}>
        <div className="p-20 justify-center drop-shadow-xl">
          <p>Front End</p>
          <h2 className="font-PageTitle font-bold text-slate-50 text-4xl">
            Web Developer
          </h2>
          <p className=" mt-3 font-PageTitle text-slate-300">
            TypeScrip | React | Next.js
          </p>

          <p className="mt-5 font-PageTitle text-slate-50">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
            veritatis deserunt officia nesciunt distinctio at eos ipsam rem qui
            reiciendis id. Fuga doloribus voluptatem iste adipisci ut beatae
            veritatis pariatur! Lorem, ipsum dolor sit amet consectetur
            adipisicing elit. Aliquid doloribus temporibus aut odit dolorem
            veniam qui laudantium nisi accusantium quasi nam, veritatis
            molestiae debitis fuga nostrum facilis assumenda. Dicta, temporibus?
          </p>
        </div>
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
